name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail"
database_id = "93ee203d-0336-4c43-b262-d8baace697e6"

[[kv_namespaces]]
binding = "kv"
id = "f6c918e2164243d9bd9f135a7b2f29cf"

[[r2_buckets]]
binding = "r2"
bucket_name = "cloud-mail-r2"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[[send_email]]
name = "EMAIL"

[vars]
orm_log = false
domain = '["owaa.ai","blizzarddelights.com"]'
admin = "admin@blizzarddelights.com"
jwt_secret = "BduFfk8j8P9WM9ImhkjD7fMS8RaOZB1v757luWaF"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
